# Chase-lift soaring operator data. Research compiled 2026-09-22.
# rental categories:
#   RENT  = rents to non-member licensed pilots (after checkout)
#   GUEST = guest / temporary / short-term / long-distance membership path
#   JOIN  = full membership required
#   CLOSED = closed or inactive
#   UNK   = unknown, call
RENTAL_LABEL = {
    "RENT": "Rents to visitors",
    "GUEST": "Guest / short-term membership",
    "JOIN": "Membership required",
    "UNK": "Unknown, call",
    "CLOSED": "Closed / inactive",
}

# access: VAN (<=4 h Friday), VANEDGE (~4 h), FLY, FAR (neither)
OPS = [
 # ---------------- NEW ENGLAND ----------------
 dict(id="GBSC", name="Greater Boston Soaring Club (home club)", kind="Club", region="New England",
  airport="Sterling (3B3)", city="Sterling, MA", lat=42.4259, lon=-71.7929, approx=False,
  access="VAN", travel="45 mi; 0:50 typical, 1:15-1:30 Fri evening",
  lift="Thermal", season="Weekends + holidays, Apr-Nov; some weekdays",
  web="https://www.soargbsc.net/", phone="(field phone not published)", email="membership@soargbsc.com",
  contacts="Tony Verhulst (groups.io); Dwight Schirmer (treasurer); Ken Flaton (evening ground school)",
  rental="JOIN", rank=2,
  procedure="Members only; no rental to non-members. Once rated: checkout in each two-seater (front and back seat) and a cockpit checkout before each single-seater. Club flights limited to 1 h. Visiting private owners only: Region 1 owners pay member tow rates; others $15/day temporary membership + $60 flat tow, max 5 visits/yr, SSA required.",
  costs="Regular $600 initiation (over 2 yr) + $750/yr; 90-day trial membership exists. Tow $14 hookup + $1.60/100 ft (min 1,200 ft). Instruction free.",
  tall="You do not fit the ASK-21. Sit-test the 1-34, L-23 and ASW-19 now; the 2-33 is roomy.",
  sources="https://www.soargbsc.net/index.php/gbsc_fleet ; https://www.soargbsc.net/fee_schedule"),
 dict(id="SUGAR", name="Sugarbush Soaring", kind="Commercial-style club", region="New England",
  airport="Warren-Sugarbush (0B7)", city="Warren, VT", lat=44.1174, lon=-72.8270, approx=False,
  access="VANEDGE", travel="191 mi; 3:15 typical, 3:45-4:00 Fri",
  lift="Thermal, ridge, wave", season="7 days (closed Tue), roughly May-Oct; airport closed Nov-Apr",
  web="https://sugarbushsoaring.com/", phone="802-496-2290", email="(via website)",
  contacts="Not published", rental="RENT", rank=1,
  procedure="Publishes non-member glider rental rates (only such operator in New England). Checkout, currency and insurance rules not published (unverified): expect dual checkout in PW-6 or 2-33 plus site briefing. Ask whether a documented checkout stays valid for later visits.",
  costs="Non-member rental: PW-6U $169/h, 2-33 $85/h, 1-26E $79/h (20 min min). Non-member tow $28 + $3.30/100 ft (2,000 ft = $94). Instruction $59-86/h. Membership $875 share + $750/yr (YP 22-35: $175/yr).",
  tall="2-33 roomy; PW-6 front seat fairly roomy (sit-test).",
  sources="https://sugarbushsoaring.com/doc/rate-sheet-2026.pdf ; https://sugarbushsoaring.com/about-us/fleet-aircraft"),
 dict(id="MOHAWK", name="Mohawk Soaring Club", kind="Club", region="New England",
  airport="Harriman-and-West (AQW)", city="North Adams, MA", lat=42.6963, lon=-73.1706, approx=False,
  access="VAN", travel="~135 mi; 2:40 typical, 3:10 Fri",
  lift="Ridge (Mt Greylock, Taconics), thermal", season="Saturdays + one midweek day (usually Wed), Apr-Nov",
  web="http://www.soarmohawk.com/", phone="(not published)", email="doug.herrick at rcn.com (rides)",
  contacts="Doug Herrick (rides); Jon Goodman (president, 2022)", rental="GUEST", rank=3,
  procedure="No rental without membership. Advertises a short-term reduced-rate 'Limited membership'; $150 ride includes a 30-day limited membership with follow-up flights $50. Terms for rated pilots unverified: email ahead.",
  costs="Quarterly dues (amount unpublished); instruction free; club says average flight under $60.",
  tall="L-13 Blanik and 2-33 are roomy types.",
  sources="http://www.soarmohawk.com/membership/ ; FAA registry"),
 dict(id="POSTMILLS", name="Post Mills Soaring Club", kind="Club", region="New England",
  airport="Post Mills (2B9)", city="Post Mills, VT", lat=43.8837, lon=-72.2521, approx=False,
  access="VAN", travel="155 mi; 2:40 typical, 3:10 Fri",
  lift="Thermal", season="Weekends assumed (unverified), spring-fall",
  web="https://flypmsc.org/", phone="802-333-9401", email="andrew.e.lumley@gmail.com",
  contacts="Andy Lumley (membership + airport manager, 802-266-1355)", rental="JOIN", rank=4,
  procedure="No visitor rental; full-season membership needed for solo. Trial membership ($100/flight, one-time) and temporary student membership exist. SSA required. Cottages on field.",
  costs="$450 initiation + $450/yr. Tow $18 + $10/1,000 ft. Glider use appears included in dues. Instruction free.",
  tall="L-23 Super Blanik and 2-33 are good tall-pilot types.",
  sources="https://flypmsc.org/ ; 2025 rates Google Doc"),
 dict(id="NESA", name="New England Soaring Association", kind="Club", region="New England",
  airport="Hartness State (VSF)", city="Springfield, VT", lat=43.3437, lon=-72.5173, approx=False,
  access="VAN", travel="123 mi; 2:15 typical, 2:45 Fri",
  lift="Thermal", season="Mostly weekends, Apr-Nov",
  web="https://www.flynesa.com/", phone="(not published)", email="(web form)",
  contacts="Jim Malecha (pres.), Larry Perry (VP), Andy Kozak (sec.), Jerry Smith (treas.)", rental="JOIN", rank=5,
  procedure="No visitor rental. Join (cheap), then checkout; short-notice flying once a member.",
  costs="$300 initiation + $300/yr + SSA. Gliders $10/flight. Tow $30 pattern to $70 at 5,000 ft. Instruction free.",
  tall="2-33 and 1-34 likely fit.",
  sources="https://www.flynesa.com/about-us/our-fleet/ ; 2025 fee schedule PDF"),
 dict(id="FRANCONIA", name="Franconia Soaring Association", kind="Club", region="New England",
  airport="Franconia (1B5)", city="Franconia, NH", lat=44.1960, lon=-71.7507, approx=False,
  access="VAN", travel="151 mi; 2:30 typical, 3:00-3:30 Fri",
  lift="Thermal, ridge (Cannon/Kinsman), wave", season="Weekends + holidays, Fri by arrangement, ~May-Oct",
  web="http://www.franconiasoaring.org/", phone="603-823-5034", email="franconiasoaring@gmail.com",
  contacts="James R. David (airport manager, 603-921-1588)", rental="UNK", rank=6,
  procedure="Visitor rules unverified (membership pages blocked). Assume membership needed; call. Six CFIGs, first come first served.",
  costs="Rides $120 (3,000 ft) / $200 (5,000 ft). Membership rates not retrieved.",
  tall="Grob 103 Twin Astir is your best two-seat bet here; L-23 and 2-33 roomy.",
  sources="http://www.franconiasoaring.org/ ; FAA registry"),
 dict(id="CSA", name="Connecticut Soaring Association", kind="Club", region="New England",
  airport="Windham (IJD)", city="Windham, CT", lat=41.7440, lon=-72.1802, approx=False,
  access="VAN", travel="84 mi; 1:30 typical, 2:00 Fri",
  lift="Thermal", season="~Apr-Nov; midweek program since 2024",
  web="https://www.ctsoaring.org/", phone="860-202-1866", email="contact@ctsoaring.org",
  contacts="Not published", rental="JOIN", rank=7,
  procedure="Must join; terms unpublished. Short of CFIGs and tow pilots.",
  costs="Not published.",
  tall="FAQ: cannot accommodate anyone over 6 ft 1 in / 220 lb (written for passengers). Poor fit.",
  sources="https://www.ctsoaring.org/our-fleet ; https://www.ctsoaring.org/faq"),
 dict(id="GORHAM", name="Mt Washington Wave Camp (GBSC/Franconia/Post Mills)", kind="Event", region="New England",
  airport="Gorham (2G8)", city="Gorham, NH", lat=44.3931, lon=-71.1967, approx=False,
  access="VANEDGE", travel="183 mi; 3:15 typical, 3:45-4:15 Fri",
  lift="Wave (Mt Washington)", season="~10 days mid-October (Columbus Day)",
  web="https://www.soargbsc.com/wave/MtWashBrief.pdf", phone="(via GBSC)", email="(via GBSC)",
  contacts="Run jointly by host clubs", rental="JOIN", rank=0,
  procedure="An event, not an operator. Fly your own club's gliders; oxygen and wave-window checkouts apply.",
  costs="Per club.", tall="Per club fleet.", sources="https://www.soargbsc.com/wave/MtWashBrief.pdf"),
 dict(id="SANFORD", name="Sanford Soaring", kind="Club?", region="New England",
  airport="Sanford Seacoast (SFM)", city="Sanford, ME", lat=43.3938, lon=-70.7080, approx=False,
  access="VAN", travel="92 mi; 1:40 typical, 2:15 Fri", lift="Thermal, sea breeze",
  season="Unknown", web="https://www.facebook.com/sanfordsoaring/", phone="", email="",
  contacts="", rental="CLOSED", rank=0,
  procedure="Website not updated since 2019; no club-registered gliders found. Status unknown.",
  costs="", tall="", sources="Facebook page"),
 dict(id="SPIRIT", name="Spirit Soaring (motorglider rides)", kind="Commercial", region="New England",
  airport="Knox County (RKD)", city="Owls Head, ME", lat=44.0601, lon=-69.0997, approx=False,
  access="VANEDGE", travel="195 mi; 3:15 typical, 3:45-4:00 Fri", lift="Coastal",
  season="Unknown", web="https://www.spiritsoaring.org/", phone="", email="",
  contacts="Dave Miramant", rental="CLOSED", rank=0,
  procedure="Rides only in a Grob 109 motorglider; website no longer resolves. Not a rental option.",
  costs="", tall="", sources="Reviews to 2020"),
 # ---------------- NY / NJ / PA ----------------
 dict(id="WURTS", name="Wurtsboro Airport / Wurtsboro Flight Mgmt", kind="Commercial", region="NY/NJ/PA",
  airport="Wurtsboro-Sullivan County (N82)", city="Wurtsboro, NY", lat=41.5972, lon=-74.4583, approx=False,
  access="VANEDGE", travel="216 mi; 3:30 typical, 4:00-4:15 Fri",
  lift="Ridge (Shawangunk), thermal", season="7 days, year-round (weather)",
  web="https://www.wurtsboroairport.com/", phone="(845) 888-2791", email="info@wurtsboroairport.com",
  contacts="Not published", rental="RENT", rank=1,
  procedure="Public commercial rental. Rental-requirements page could not be read: expect instructor checkout, possibly minimum hours. Do one checkout day before relying on short-notice trips; ask currency rule.",
  costs="Rental: Grob 103 $75/h, 2-33 $67/h, 1-26E $55/h. Tow to 2,500 ft $74.07, +$20/1,000 ft. Instruction $65-67/h.",
  tall="2-33 good; Grob 103 depends on proportions; 1-26 poor.",
  sources="https://www.wurtsboroairport.com/rates"),
 dict(id="ACA", name="Aero Club Albatross", kind="Club", region="NY/NJ/PA",
  airport="Blairstown (1N7) + Wurtsboro (N82)", city="Blairstown, NJ", lat=40.9712, lon=-74.9975, approx=False,
  access="FAR", travel="266 mi to Blairstown; 4:45-5:00 Fri (Wurtsboro ~4:00)",
  lift="Ridge (Kittatinny, Shawangunk), thermal", season="Wurtsboro 7 days; Blairstown weekends",
  web="https://www.aeroclubalbatross.org/", phone="(973) 294-5146", email="AeroClubAlbatross@gmail.com",
  contacts="Not published", rental="JOIN", rank=6,
  procedure="Full membership (licensed pilots): apply, attend a monthly meeting (3rd Thu, Denville NJ), wing-runner course, checkout. No hourly glider charge afterwards.",
  costs="$1,000 initiation (or $250/yr x4) + $138 dues + $530/yr flight fee + SSA. Tow 2,000 ft $38 with season pass.",
  tall="2-33 and LS-4 good; Twin Astir depends on proportions.",
  sources="https://www.aeroclubalbatross.org/memberships/"),
 dict(id="JRS", name="Jersey Ridge Soaring", kind="Commercial", region="NY/NJ/PA",
  airport="Blairstown (1N7)", city="Blairstown, NJ", lat=40.9730, lon=-74.9950, approx=True,
  access="FAR", travel="266 mi; 4:15 typical, 4:45-5:00 Fri; or PHL + 1:45",
  lift="Ridge (Kittatinny), thermal", season="Weekends, year-round; tows 7 days",
  web="https://www.jerseyridgesoaring.com/", phone="(908) 362-1239", email="info@jerseyridgesoaring.com",
  contacts="Kevin & Brenda Martin (owners); Michael Friedman (chief instructor)", rental="UNK", rank=8,
  procedure="Website lists tows for private owners and ACA members; no solo-rental policy published. Call about checkout + rental of 2-33 / 1-26.",
  costs="Lessons $130-160.", tall="2-33 and 2-32 good.",
  sources="http://www.jerseyridgesoaring.com/Lessons.html"),
 dict(id="ASA", name="Adirondack Soaring Association", kind="Club", region="NY/NJ/PA",
  airport="Saratoga County (5B2)", city="Ballston Spa, NY", lat=43.0512, lon=-73.8612, approx=True,
  access="VAN", travel="193 mi; 3:15 typical, 3:45 Fri",
  lift="Thermal, some ridge", season="Every weekend + some weekdays, Apr-Nov",
  web="https://www.adirondacksoaring.com/", phone="(518) 693-6849", email="(web)",
  contacts="Eric Davenport (pres.); Tim Hanke (dir. of ops)", rental="GUEST", rank=5,
  procedure="Long-Distance membership (live 120+ mi away): full fleet access; book on Click N Glide. Board approval + SSA. Checkout Grob 103 then Grob 102.",
  costs="Long-Distance $650 initiation + $15/month; gliders + instruction included; tows only ($40 to 2,000 ft, 2022).",
  tall="All-Grob fleet: Grob 102 roomiest; Grob 103 depends on proportions.",
  sources="https://www.adirondacksoaring.com/membership"),
 dict(id="HHSC", name="Harris Hill Soaring Corp", kind="Club", region="NY/NJ/PA",
  airport="Harris Hill Gliderport (4NY8)", city="Elmira, NY", lat=42.1209, lon=-76.9011, approx=False,
  access="FLY", travel="5:30 drive; or SYR + 1:45 / BUF + 2:30",
  lift="Ridge, thermal", season="~Apr-Oct; weekends (daily Jun-mid Aug)",
  web="https://harrishillsoaring.org/", phone="(607) 734-0641", email="newmember@ / training@harrishillsoaring.org",
  contacts="", rental="GUEST", rank=3,
  procedure="'Board approved guest' category: $20/day, rental $50/h. Email ahead for guest approval; checkout in 2-33, 1-34 or Duo Discus. Non-members: tows only.",
  costs="Guest $20/day; rental $50/h; tow $20 + $30/1,000 ft. Senior member $300 + $30/mo; rental $9-25/h.",
  tall="2-33 and Duo Discus good; ASK-21 no.",
  sources="https://harrishillsoaring.org/wp-content/uploads/2026/02/2026-rates.pdf"),
 dict(id="FLSC", name="Finger Lakes Soaring Club", kind="Club", region="NY/NJ/PA",
  airport="Dansville (DSV)", city="Dansville, NY", lat=42.571, lon=-77.713, approx=True,
  access="FLY", travel="BUF/ROC + ~1:00", lift="Thermal", season="Weekends 9-5, Apr-Nov",
  web="https://flsc.org/", phone="(585) 335-5849", email="contact@flsc.org",
  contacts="Rick Lafford (airport mgr, 585-444-3612)", rental="GUEST", rank=7,
  procedure="Long Distance membership; 'Guest' status for pilots of other SSA clubs (orientation). Seasonal check ride; 1-26 needs 15 flights in type.",
  costs="Long Distance $550 ($200 refundable) + $15/mo. Tow $18/1,000 ft; winch $8.50.",
  tall="Grob 102 and 2-33 good.", sources="https://flsc.org/MembershipJoinUs.php"),
 dict(id="VSC", name="Valley Soaring Club", kind="Club", region="NY/NJ/PA",
  airport="Randall (06N)", city="Middletown, NY", lat=41.4319, lon=-74.3916, approx=False,
  access="VANEDGE", travel="~3:30 typical, ~4:00 Fri", lift="Thermal", season="Weekends + Mon holidays, Apr-Dec",
  web="(login-only site)", phone="(845) 564-2054", email="", contacts="", rental="UNK", rank=10,
  procedure="Membership terms unpublished; call.", costs="", tall="2-33 good.", sources="FlightSchoolList; FAA registry"),
 dict(id="LISA", name="Long Island Soaring Association", kind="Club", region="NY/NJ/PA",
  airport="Brookhaven Calabro (HWV)", city="Shirley, NY", lat=40.822, lon=-72.869, approx=True,
  access="FAR", travel="4+ h", lift="Thermal (flat coastal)", season="Weekends, some Wed",
  web="https://longislandsoaring.com/", phone="631-578-8596", email="", contacts="", rental="JOIN", rank=14,
  procedure="3 prepaid guest flights + 2 meetings before joining. Poor fit for chasing lift.",
  costs="Guest flight $120 then $60; $800 + $66/mo; tow $21 to 1,000 ft.", tall="2-33 good.",
  sources="https://longislandsoaring.com/fees"),
 dict(id="VANSANT", name="Van Sant Airport / Bird of Paradise", kind="Commercial", region="NY/NJ/PA",
  airport="Van Sant (9N1)", city="Erwinna, PA", lat=40.4842, lon=-75.0997, approx=False,
  access="FLY", travel="PHL + 1:15 (drive 5:00+)", lift="Thermal, some ridge", season="Tue-Sun 9-4, year-round",
  web="https://vansantairport.com/", phone="(610) 847-1119", email="", contacts="Office (610) 847-8494",
  rental="RENT", rank=2,
  procedure="'Licensed glider pilots may also rent.' Checkout/currency rules not published; expect a checkout.",
  costs="Rental 2-33 $80/h, 2-32 $80/h + tows. Tow $50 (1,000) / $60 (2,000) / $65 (3,000) / $100 (5,000). Instruction $120 + tow.",
  tall="2-33 and 2-32 both roomy.", sources="https://vansantairport.com/rides-and-rental-prices/"),
 dict(id="TIGERS", name="Soaring Tigers", kind="Club", region="NY/NJ/PA",
  airport="Van Sant (9N1)", city="Erwinna, PA", lat=40.4860, lon=-75.0975, approx=True,
  access="FLY", travel="PHL + 1:15", lift="Thermal", season="Wed-Sun",
  web="https://soaringtigers.org/", phone="(610) 847-1119", email="", contacts="", rental="JOIN", rank=13,
  procedure="Annual membership only; tows only after that.", costs="$700/yr after solo; tows $35-90.",
  tall="Pilot weight limits 191-385 lb by glider.", sources="https://soaringtigers.org/memberinfo.html"),
 dict(id="PGC", name="Philadelphia Glider Council", kind="Club", region="NY/NJ/PA",
  airport="Philadelphia Gliderport (3PA2)", city="Hilltown, PA", lat=40.3312, lon=-75.2481, approx=False,
  access="FLY", travel="PHL + ~1:00", lift="Thermal", season="Weekends",
  web="https://pgcsoaring.org/", phone="215-334-5980", email="", contacts="", rental="JOIN", rank=11,
  procedure="Full membership only.", costs="$1,090/yr + $700 entry + $100 bond; tows ~$35.",
  tall="Grob 102 roomy; Grob 103s depend on proportions.", sources="https://pgcsoaring.org/glider-club-membership.php"),
 dict(id="BSA", name="Brandywine Soaring Association", kind="Club", region="NY/NJ/PA",
  airport="New Garden (N57)", city="Toughkenamon, PA", lat=39.831, lon=-75.770, approx=True,
  access="FLY", travel="PHL + ~1:00", lift="Thermal", season="Wed + weekends, May-Oct",
  web="https://www.brandywinesoaring.org/", phone="", email="membership@brandywinesoaring.org", contacts="",
  rental="GUEST", rank=9, procedure="Non-resident membership (100+ mi); waiting list, faster for rated pilots.",
  costs="$500 + $35/mo; tow 3,000 ft $44.", tall="L-23 roomy; ASK-21 no.", sources="brandywinesoaring.org membership page"),
 dict(id="PSA", name="Pittsburgh Soaring Association", kind="Club", region="NY/NJ/PA",
  airport="Greene County (WAY)", city="Waynesburg, PA", lat=39.900, lon=-80.133, approx=True,
  access="FLY", travel="PIT + ~1:00", lift="Thermal", season="Weekends",
  web="http://pghsoar.org/", phone="", email="", contacts="", rental="GUEST", rank=4,
  procedure="'Temporary memberships are available for visiting pilots' (price unpublished).",
  costs="Rental $10/h; tow $25 + $5/1,000 ft; full $60/mo + ~$500 buy-in.",
  tall="Grob 102 and L-23 good.", sources="http://pghsoar.org/fly-with-us/"),
 dict(id="MASA", name="Mid-Atlantic Soaring Association", kind="Club", region="Mid-Atlantic",
  airport="Fairfield (W73)", city="Fairfield, PA", lat=39.7570, lon=-77.3514, approx=False,
  access="FLY", travel="BWI/IAD + ~1:30", lift="Thermal, ridge, wave", season="Mar-Nov",
  web="https://midatlanticsoaring.org/", phone="717-642-9907 (airport)", email="joinus@midatlanticsoaring.org",
  contacts="Mark Philip (airport mgr)", rental="JOIN", rank=12,
  procedure="Full membership, provisional first year, 5 duty days. No visitor membership. Pilot weight ~154-240 lb.",
  costs="$1,000 initiation + $695/yr + SSA.", tall="Mostly ASK-21; 2-33A only likely fit.",
  sources="midatlanticsoaring.org join page"),
 # ---------------- MID-ATLANTIC / SE / MIDWEST ----------------
 dict(id="SKYLINE", name="Skyline Soaring Club", kind="Club", region="Mid-Atlantic",
  airport="Front Royal (FRR); at Petersburg WV (W99) from 16 Sep 2026", city="Front Royal, VA", lat=38.9175, lon=-78.2535, approx=True,
  access="FLY", travel="IAD + ~1:00 (Petersburg ~2:45)", lift="Thermal, ridge; wave at Petersburg", season="Weekends + some weekdays",
  web="https://www.skylinesoaring.org/", phone="", email="welcome@skylinesoaring.org", contacts="",
  rental="GUEST", rank=2,
  procedure="'Visiting Member' $10/day for members of SSA-affiliated clubs, max 5 days/yr. Introductory $75 for 45 days. Email with SSA number + logbook; expect checkout.",
  costs="ASK-21 $39/h, Discus CS $36/h (capped 3 h), PW-5 $24/h. Tow $30 to 1,000 ft + $1/100 ft.",
  tall="ASK-21 won't fit; Discus CS medium (sit-test).", sources="https://www.skylinesoaring.org/cms/ssc-documents/dues-fees/"),
 dict(id="ESC", name="Eastern Soaring Center", kind="Commercial", region="Mid-Atlantic",
  airport="Grant County (W99)", city="Petersburg, WV", lat=38.9914, lon=-79.1456, approx=True,
  access="FLY", travel="IAD + ~2:45", lift="Thermal, ridge, wave (FL230 window)", season="Closed for 2026",
  web="https://www.easternsoaringcenter.com/", phone="304-851-4106", email="gliding@EasternSoaringCenter.com",
  contacts="Brian Collins (owner, DPE)", rental="CLOSED", rank=0,
  procedure="Rents to rated pilots with an ESC airfield/winch checkride in last 12 months. Closed for 2026 season; watch for 2027.",
  costs="ASK-13 $55/h; winch $30-60.", tall="ASK-13 roomy.", sources="https://www.easternsoaringcenter.com/"),
 dict(id="SVS", name="Shenandoah Valley Soaring", kind="Club", region="Mid-Atlantic",
  airport="Rockfish Gliderport (VG22)", city="Nellysford, VA", lat=37.8788, lon=-78.8935, approx=False,
  access="FLY", travel="IAD/DCA + ~2:45-3:00", lift="Thermal, ridge", season="Weekends, year-round",
  web="https://www.svsoar.org/", phone="", email="(web form)", contacts="", rental="GUEST", rank=6,
  procedure="3-month introductory membership (from demo flight). Height limit under 6'5\", 230 lb.",
  costs="Unpublished.", tall="Under 6'5\" limit.", sources="https://www.svsoar.org/faqs.html"),
 dict(id="BRSS", name="Blue Ridge Soaring Society", kind="Club", region="Mid-Atlantic",
  airport="New Castle (VA85)", city="New Castle, VA", lat=37.4835, lon=-80.0998, approx=False,
  access="FLY", travel="IAD/CLT/RDU + 3:30-4:00", lift="Ridge, wave (to 23,000 ft), thermal", season="Weekends",
  web="https://www.brss.net/", phone="540-864-5800 (airport owner)", email="(web form)", contacts="Lanier Frantz (airport owner)",
  rental="GUEST", rank=5, procedure="Monthly guest memberships, club approval. Tows and instruction members only.",
  costs="Unpublished.", tall="ASK-21, LS-4, LS-6: poor fit.", sources="https://www.brss.net/visitor-info/"),
 dict(id="TSS", name="Tidewater Soaring Society", kind="Club", region="Mid-Atlantic",
  airport="Garner (3VA8)", city="Windsor, VA", lat=36.8563, lon=-76.6822, approx=False,
  access="FLY", travel="RDU + 2:45", lift="Thermal", season="Weekends, year-round",
  web="https://tss.fyi/", phone="757-377-6174 (landing permission)", email="", contacts="W.E. Laine Jr.",
  rental="JOIN", rank=0, procedure="Membership only.", costs="$300 + $200 deposit + $45/mo + SSA.",
  tall="2-33A good.", sources="http://www.tidewatersoaring.org/membership.html"),
 dict(id="BHS", name="Bermuda High Soaring", kind="Commercial + club", region="Southeast",
  airport="Bermuda High Gliderport (SC79)", city="Jefferson, SC", lat=34.6113, lon=-80.4498, approx=False,
  access="FLY", travel="CLT + 1:15", lift="Thermal", season="Weekends 10-5, year-round",
  web="https://bermudahighsoaring.com/", phone="(803) 475-7627", email="", contacts="Jayne Ewing Reid; Frank Reid",
  rental="UNK", rank=4, procedure="'Not scheduling instruction at this time'; members first. Call about rental.",
  costs="Ride $120 (2-33); weight limit 230-240 lb.", tall="2-33 and Duo Discus good.",
  sources="https://bermudahighsoaring.com/contact-us.html"),
 dict(id="CAROLINA", name="Carolina Soaring Association", kind="Club", region="Southeast",
  airport="Spartanburg Downtown (SPA)", city="Spartanburg, SC", lat=34.9157, lon=-81.9565, approx=True,
  access="FLY", travel="CLT + 1:15", lift="Thermal", season="Weekends",
  web="https://carolinasoaring.org/", phone="864-256-1741", email="", contacts="", rental="JOIN", rank=0,
  procedure="Contact before a trip; no visitor option published.",
  costs="$250 + $82/mo; gliders $0/h; aerotow $7 + $2.17/100 ft; winch $12.", tall="Grob 103 roomy.",
  sources="https://carolinasoaring.org/rates/"),
 dict(id="NCSA", name="North Carolina Soaring Association", kind="Club", region="Southeast",
  airport="Crooked Creek (7NC5)", city="Bunn, NC", lat=35.9312, lon=-78.2448, approx=False,
  access="FLY", travel="RDU + 0:45", lift="Thermal", season="Every weekend day",
  web="https://soaringnc.org/", phone="919-215-1356 (field owner)", email="info@soaringnc.org", contacts="Frank Swett",
  rental="JOIN", rank=0, procedure="'Drop by anytime we are flying'; fleet and rates unpublished.", costs="", tall="",
  sources="https://soaringnc.org/"),
 dict(id="MGSA", name="Mid-Georgia Soaring Association", kind="Club", region="Southeast",
  airport="Monroe (D73)", city="Monroe, GA", lat=33.7823, lon=-83.6926, approx=True,
  access="FLY", travel="ATL + 1:00", lift="Thermal", season="Most weekends",
  web="https://www.soar-mgsa.org/", phone="", email="membershipinfo@soar-mgsa.org", contacts="", rental="JOIN", rank=0,
  procedure="Membership only.", costs="$500 + $450/yr + $500 capital note + SSA; tow 2,000 ft ~$50.",
  tall="ASK-21s; Grob 102 maybe.", sources="https://www.soar-mgsa.org/membershipinfo"),
 dict(id="CHIL", name="Chilhowee Gliderport", kind="Commercial", region="Southeast",
  airport="Chilhowee (92A)", city="Benton, TN", lat=35.2265, lon=-84.5849, approx=False,
  access="FLY", travel="ATL + 2:15; BNA + 3:00", lift="Thermal (spring-fall), ridge (fall-spring), occasional wave",
  season="Fri-Sun 11:00-sunset, year-round",
  web="https://www.chilhowee.com/", phone="423-338-2000 (cell 423-506-9015)", email="info@chilhowee.com",
  contacts="Sarah Arnold (bookings)", rental="RENT", rank=1,
  procedure="Commercial hourly rental, no membership. Expect dual checkout (2-33A) first visit. Block account $1,000 buys $1,100 credit (forfeited after 1 yr idle). After that, call Thursday.",
  costs="2-33A $48/h, PW-6U $72/h, 1-26E $40/h, PW-5 $48/h (15 min min). Tow $20 + $2/100 ft ($40 min). Instruction $60/h.",
  tall="2-33A best; PW-6U fairly roomy; 2-32 very roomy (dual only).", sources="https://www.chilhowee.com/rates.html"),
 dict(id="EAGLEVILLE", name="Eagleville Soaring Club", kind="Club", region="Southeast",
  airport="Puckett Gliderport (50M)", city="Eagleville, TN", lat=35.6894, lon=-86.6150, approx=False,
  access="FLY", travel="BNA + 0:45", lift="Thermal", season="Most weekends, year-round",
  web="https://eaglevillesoaring.org/", phone="800-306-6690", email="info@eaglevillesoaring.org", contacts="",
  rental="JOIN", rank=0, procedure="No visitor option published.", costs="",
  tall="ASK-21s, LS-4: poor fit ('height limited if significantly above 6 ft').", sources="https://eaglevillesoaring.org/"),
 dict(id="SKYSOAR", name="Sky Soaring", kind="Club", region="Midwest",
  airport="Sky Soaring (55LL)", city="Hampshire, IL", lat=42.1542, lon=-88.5115, approx=False,
  access="FLY", travel="ORD + 0:50", lift="Thermal", season="Mid-Apr-Oct",
  web="https://skysoaring.com/", phone="(847) 683-7627", email="", contacts="", rental="JOIN", rank=0,
  procedure="Accepting 1 new member this season; no visitor option.",
  costs="$250 + $725/yr + $1,000 buy-in; tows $25-55.", tall="2-33A, KR-03 Puchatek good.", sources="https://skysoaring.com/membership/"),
 dict(id="CGC", name="Chicago Glider Club", kind="Club", region="Midwest",
  airport="Chicago Glider Club (IL59)", city="Minooka, IL", lat=41.4320, lon=-88.2473, approx=False,
  access="FLY", travel="MDW + 0:50", lift="Thermal", season="Apr-Oct",
  web="http://www.chicagogliderclub.org/", phone="630-854-9456", email="", contacts="Ron Ridenour (manager)",
  rental="JOIN", rank=0, procedure="Sponsor required; long-term commitment.", costs="$1,200 + $552/yr; ships $36-40/h.",
  tall="Duo Discus front seat roomy.", sources="chicagogliderclub.org fees"),
 dict(id="CCSC", name="Caesar Creek Soaring Club", kind="Club", region="Midwest",
  airport="Caesar Creek Gliderport (2OH9)", city="Waynesville, OH", lat=39.4767, lon=-84.0938, approx=False,
  access="FLY", travel="CMH + 1:15", lift="Thermal", season="Weekends + Wed, year-round",
  web="https://www.soarccsc.com/", phone="513-932-7627", email="ccsc@soarccsc.com", contacts="", rental="JOIN", rank=0,
  procedure="Full membership required to act as PIC.", costs="$1,000 + $38/mo + 12 SSD shares ($100 ea).",
  tall="2-33s, Grob 102.", sources="https://www.soarccsc.com/membership/"),
 dict(id="SANDHILL", name="Sandhill Soaring Club", kind="Club", region="Midwest",
  airport="Richmond Field (69G)", city="Gregory, MI", lat=42.4420, lon=-84.0643, approx=False,
  access="FLY", travel="DTW + 1:00", lift="Thermal", season="Weekends Apr-Nov + weekdays",
  web="https://www.sandhillsoaring.org/", phone="734-498-2075 (field mgr)", email="", contacts="Michael Campbell (field mgr)",
  rental="GUEST", rank=3, procedure="'Short-term Guest Membership may be arranged for licensed soaring pilots.' Price unpublished.",
  costs="Tow min $26 + $1/100 ft above 1,000 ft.", tall="DG-505, Grob 103, 2-33: best tall-pilot club fleet.",
  sources="https://www.sandhillsoaring.org/join"),
 # ---------------- FLORIDA / TEXAS / WEST ----------------
 dict(id="SEMINOLE", name="Seminole-Lake Gliderport", kind="Commercial", region="Florida",
  airport="Seminole Lake Gliderport (6FL0)", city="Clermont, FL", lat=28.4058, lon=-81.8379, approx=False,
  access="FLY", travel="MCO + 0:45", lift="Thermal, sea-breeze convergence; best Mar-May", season="Tue-Sun (winter), Wed-Sun (summer)",
  web="https://www.soarfl.com/", phone="352-394-5450", email="office@soarfl.com", contacts="", rental="RENT", rank=1,
  procedure="By schedule only; call ahead. Renters must carry $40,000 hull insurance. Checkout rules unpublished. Gliderport listed for sale (small continuity risk).",
  costs="Grob 103 $125/h, L-23 $120/h. Tow rates on request. Rides $180-260.",
  tall="L-23 and Grob 103 good.", sources="https://www.soarfl.com/airfield_info/ ; https://www.soarfl.com/our_aircraft"),
 dict(id="TBSS", name="Tampa Bay Soaring Society", kind="Club", region="Florida",
  airport="Zephyrhills (ZPH)", city="Zephyrhills, FL", lat=28.2267, lon=-82.1556, approx=False,
  access="FLY", travel="TPA + 0:45", lift="Thermal", season="Wed, Sat, Sun, year-round",
  web="https://www.tampabaysoaring.com/", phone="813-780-0031", email="", contacts="", rental="JOIN", rank=11,
  procedure="Apply in person; full membership only.", costs="$800 + $250/6 mo; tow $20 + $1/100 ft; gliders free.",
  tall="L-23s good.", sources="https://www.tampabaysoaring.com/membership/"),
 dict(id="MIAMI", name="Miami Gliders", kind="Commercial", region="Florida",
  airport="Homestead General (X51)", city="Homestead, FL", lat=25.4988, lon=-80.5543, approx=True,
  access="FLY", travel="MIA + 0:50; FLL + 1:15", lift="Thermal", season="Call",
  web="https://www.miamigliders.com/", phone="(786) 243-7640", email="fly@miamigliders.com", contacts="", rental="RENT", rank=3,
  procedure="Solo rental rates published; requirements not. Call about insurance + checkout.",
  costs="L-23 $90/h, 2-32 $90/h, B-4 $75/h. Tow $55 (2,000 ft) to $75 (3,000 ft).", tall="L-23 and 2-32 good.",
  sources="https://www.miamigliders.com/rates.html"),
 dict(id="TSA", name="Texas Soaring Association", kind="Club", region="Texas",
  airport="TSA Gliderport (TA11)", city="Midlothian, TX", lat=32.3835, lon=-97.0142, approx=False,
  access="FLY", travel="DFW + 0:50 (Tier C fares)", lift="Thermal; best Apr-Sep", season="Thu, Sat, Sun, year-round",
  web="https://texassoaring.org/", phone="972-775-4234", email="(web)", contacts="Marco (membership director)", rental="GUEST", rank=5,
  procedure="Visiting Licensed Pilot Membership (under 30 days); SSA + glider rating. Details in members memo. Also $30 Texas XC Series = temporary member at participating clubs.",
  costs="Full $500 + $65/mo.", tall="ASK-21, PW-5, 1-26: poor fit; Duo Discus maybe.", sources="https://texassoaring.org/page-18133"),
 dict(id="SCH", name="Soaring Club of Houston", kind="Club", region="Texas",
  airport="SCH Gliderport (89TA)", city="Waller, TX", lat=30.1927, lon=-95.9633, approx=False,
  access="FLY", travel="IAH + 1:00", lift="Thermal", season="Sat-Sun",
  web="https://sites.google.com/site/soaringclubofhouston/", phone="", email="", contacts="", rental="GUEST", rank=6,
  procedure="'Guest' and 'One-Day' memberships exist; ask what they allow.", costs="2-33 $0.20/min; L-23/L-33 $0.40/min; ASK-21 $0.60/min.",
  tall="L-23 and 2-33 good.", sources="SCH membership information page"),
 dict(id="FLF", name="Fault Line Flyers", kind="Club", region="Texas",
  airport="FLF field (private)", city="Briggs/Bertram, TX", lat=30.88, lon=-97.93, approx=True,
  access="FLY", travel="AUS + 1:15", lift="Thermal", season="Every weekend",
  web="https://www.faultlineflyers.com/", phone="(512) 489-0460", email="soar.flf@gmail.com", contacts="Bins Ely (president)",
  rental="GUEST", rank=8, procedure="Guest membership at $46/mo for pilots from other clubs; but site says club aircraft not for non-members. Confirm.",
  costs="Tows $25-55; Schweizers $0.25/min; Twin Astir $0.30/min.", tall="2-33 good.", sources="https://www.faultlineflyers.com/"),
 dict(id="MHG", name="Mile High Gliding", kind="Commercial", region="Mountain West",
  airport="Boulder Municipal (BDU)", city="Boulder, CO", lat=40.0394, lon=-105.2261, approx=False,
  access="FLY", travel="DEN + 0:45", lift="Mountain thermal; wave Nov-Mar", season="Wed-Sun year-round",
  web="https://www.milehighgliding.com/", phone="(303) 527-1122", email="", contacts="Andrew McKenna", rental="RENT", rank=4,
  procedure="'Rentals' advertised; fleet/terms not online. Expect mountain + density-altitude checkout and own insurance. Call.",
  costs="Not published.", tall="Unknown; back seat reported tight.", sources="Boulder Chamber listing"),
 dict(id="SSB", name="Soaring Society of Boulder", kind="Club", region="Mountain West",
  airport="Boulder Municipal (BDU)", city="Boulder, CO", lat=40.0410, lon=-105.2240, approx=True,
  access="FLY", travel="DEN + 0:45", lift="Mountain thermal, wave", season="Year-round",
  web="https://www.soarboulder.org/", phone="", email="", contacts="", rental="GUEST", rank=7,
  procedure="'Limited' membership (no initiation). Provisional until you attend a meeting; flight + written + oral checks. Book via Flightlog.",
  costs="Limited: $21/flight + $36/h. Regular $500 + $500 deposit + ~$41/mo.", tall="DG-505 best chance; ASK-21 no.",
  sources="https://www.soarboulder.org/aircraft"),
 dict(id="AZS", name="Arizona Soaring (Estrella Sailport)", kind="Commercial", region="Southwest",
  airport="Estrella Sailport (E68)", city="Maricopa, AZ", lat=33.0853, lon=-112.1610, approx=False,
  access="FLY", travel="PHX + 0:45 (Tier C fares)", lift="Desert thermal; best Oct-Apr", season="Every day, year-round (short July break)",
  web="https://azsoaring.com/", phone="(520) 568-2318", email="info@azsoaring.com", contacts="Jason (jason@azsoaring.com)",
  rental="RENT", rank=1,
  procedure="Rental open daily. Must bring own non-owner renter policy (hull min $15k-100k by type). Rental-only bookings: no deposit, no cancellation fee. Checkout rules unpublished; expect dual checkout.",
  costs="1-26E $40/h, 1-36 $45/h, 2-33A $60/h, PW-5 $50/h, Genesis 2 $70/h, G103A $75/h, ASK-21 $110/h (20 min min). Tow $60 + $1.75/100 ft. Instruction $90/h.",
  tall="G103 and 2-33 good; ASK-21 no.", sources="https://azsoaring.com/rates/ ; https://azsoaring.com/insurance-requirements/"),
 dict(id="LVVSA", name="Las Vegas Valley Soaring Association", kind="Club", region="Southwest",
  airport="Jean (0L7)", city="Jean, NV", lat=35.7683, lon=-115.3296, approx=False,
  access="FLY", travel="LAS + 0:30 (Tier C fares)", lift="Thermal Mar-Nov; wave winter", season="Weekends, year-round",
  web="https://www.lvvsa.org/", phone="702-267-7499 (rides)", email="", contacts="", rental="JOIN", rank=9,
  procedure="Join (a year's dues + SSA). No temporary membership.", costs="$72.50/mo; tows from $42.50.",
  tall="2-33A and L-23 good.", sources="https://www.lvvsa.org/new-members"),
 dict(id="USA", name="Utah Soaring Association / Soar Utah", kind="Club + commercial tow", region="Mountain West",
  airport="Heber Valley (HCR)", city="Heber City, UT", lat=40.4818, lon=-111.4288, approx=False,
  access="FLY", travel="SLC + 0:55 (Tier C fares)", lift="High thermal, wave; May-Sep", season="Seasonal",
  web="https://utahsoaring.org/", phone="801-979-8482 (CFI Lynn Alley)", email="", contacts="Lynn Alley (CFI); Dave Robinson, Soar Utah 801-580-9310",
  rental="JOIN", rank=10, procedure="Must join; licensed pilots get proficiency checkout.", costs="$500 + $800/yr; tows $65-75.",
  tall="Grob 103s workable.", sources="https://utahsoaring.org/learn-to-fly/"),
 dict(id="MERLIN", name="Merlin Aviation", kind="Commercial", region="Southwest",
  airport="Moriarty (0E0)", city="Moriarty, NM", lat=34.9782, lon=-106.0000, approx=False,
  access="FAR", travel="ABQ + 0:45 (connection likely)", lift="Very strong thermal", season="Call",
  web="https://www.merlinaviation.net/", phone="(505) 226-5556", email="info@merlinaviation.net", contacts="",
  rental="UNK", rank=0, procedure="AirNav lists rental; terms unpublished.", costs="Rides from $200.", tall="", sources="https://www.merlinaviation.net/"),
 dict(id="SOARNV", name="SoaringNV", kind="Commercial", region="Southwest",
  airport="Minden-Tahoe (MEV)", city="Minden, NV", lat=39.0003, lon=-119.7508, approx=False,
  access="FAR", travel="No BOS nonstop to RNO", lift="Wave, thermal (world class)", season="7 days, year-round",
  web="https://soaringnv.com/", phone="(775) 790-8041", email="", contacts="", rental="RENT", rank=0,
  procedure="Renter's insurance proof; XC checkout before leaving glide range. Reference only (no Friday-night access).",
  costs="", tall="Duo Discus/Duo X.", sources="https://soaringnv.com/wp-content/uploads/2019/11/2020-RENTAL-AGREEMENT.pdf"),
]

# Fleet: (op id, model, registration, seats, rate, rentable-by-visitor, tall-pilot note)
FLEET = [
 ("GBSC","Schleicher ASK-21","N421GB",2,"$25/h members","Members","Did not fit you"),
 ("GBSC","Schleicher ASK-21","N721RC",2,"$25/h members","Members","Did not fit you"),
 ("GBSC","Schweizer 2-33A","N1225S",2,"$14/h members","Members","Roomy"),
 ("GBSC","LET L-23 Super Blanik","",2,"$14/h members","Members","Roomy; sit-test"),
 ("GBSC","Schleicher ASW-19B","",1,"$20/h, 2 h limit","Members","Tight above ~6'2\""),
 ("GBSC","LET L-33 Solo","",1,"$10/h, 2 h limit","Members","Probably OK"),
 ("GBSC","Schweizer 1-34","N1156S",1,"$10/h","Members","Generally good"),
 ("GBSC","Schweizer 1-26E","N33917",1,"$10/h","Members","Small"),
 ("SUGAR","PZL PW-6U","N16VT",2,"$169/h non-member; $50 member","Yes","Front seat fairly roomy"),
 ("SUGAR","PZL PW-6U","N777VT",2,"$169/h non-member; $50 member","Yes","Front seat fairly roomy"),
 ("SUGAR","Schweizer 2-33","N2743H",2,"$85/h non-member; $40 member","Yes","Roomy"),
 ("SUGAR","Schweizer 2-33","",2,"$85/h non-member; $40 member","Yes","Roomy"),
 ("SUGAR","Schweizer 1-26E","N1107S",1,"$79/h non-member; $40 member","Yes","Small"),
 ("MOHAWK","LET L-13 Blanik","N336MS",2,"","Members","Roomy"),
 ("MOHAWK","Schweizer 2-33A","N1186S",2,"","Members","Roomy"),
 ("MOHAWK","Schweizer 2-33A","N2039T",2,"","Members","Roomy"),
 ("MOHAWK","Schweizer 2-22E","N2729Z",2,"","Members","Small; may be inactive"),
 ("MOHAWK","Schweizer 1-26E","N65947",1,"","Members","Small"),
 ("MOHAWK","Schweizer 1-23H-15","N10388",1,"","Members","Small; may be inactive"),
 ("POSTMILLS","Schweizer 2-33A","N17967",2,"In dues","Members","Roomy"),
 ("POSTMILLS","LET L-23 Super Blanik","N303BA",2,"In dues","Members","Roomy"),
 ("POSTMILLS","Schweizer 1-26E","N1115S",1,"In dues","Members","Small"),
 ("POSTMILLS","HpH 304C","N304PM",1,"In dues","Members","Unverified"),
 ("NESA","Schweizer 2-33","N2041T",2,"$10/flight","Members",""),
 ("NESA","Schweizer 2-33A","N1242S",2,"$10/flight","Members",""),
 ("NESA","Schweizer 1-34","N7660",1,"$10/flight","Members",""),
 ("NESA","Schweizer 1-26E","N65948",1,"$10/flight","Members","Small"),
 ("FRANCONIA","Grob G103 Twin Astir","N103GV",2,"","Members?","Large cockpit; best bet"),
 ("FRANCONIA","LET L-23 Super Blanik","N118BB",2,"","Members?","Roomy"),
 ("FRANCONIA","Schweizer 2-33A","N33968",2,"","Members?","Roomy"),
 ("FRANCONIA","Schweizer 2-33A","N7776S",2,"","Members?","Roomy"),
 ("FRANCONIA","Schweizer 1-26","N2775Z",1,"","Members?","Small"),
 ("FRANCONIA","Schweizer 1-26E","N606GF",1,"","Members?","Small"),
 ("FRANCONIA","Pilatus B4","N76PS",1,"","Members?","Smallish"),
 ("CSA","Schweizer 2-33A","N2930H",2,"","Members",""),
 ("CSA","Schweizer 2-33A","N1228S",2,"","Members",""),
 ("CSA","Schweizer 1-26E","N2517H",1,"","Members","Small"),
 ("CSA","Schweizer 1-34","N1164S",1,"","Members",""),
 ("WURTS","Grob G103A Twin II","",2,"$75/h","Yes","Depends on proportions"),
 ("WURTS","Schweizer 2-33A","N2656H",2,"$67/h","Yes","Roomy"),
 ("WURTS","Schweizer 2-33A","N65828",2,"$67/h","Yes","Roomy"),
 ("WURTS","Schweizer 1-26E","N33898",1,"$55/h","Yes","Little headroom"),
 ("ACA","Grob G103 Twin Astir","N103GT",2,"Tows only","Members","Depends on proportions"),
 ("ACA","Rolladen-Schneider LS-4A","N3YA",1,"Tows only","Members","Roomy"),
 ("ACA","Pilatus B4","N21TU",1,"Tows only","Members",""),
 ("ACA","Schweizer 1-34","N134TM",1,"Tows only","Members",""),
 ("ACA","Schweizer 1-26 (x4)","N1118S, N17950, N2994H, N2767R",1,"Tows only","Members","Little headroom"),
 ("ACA","Schweizer 2-33A","N17867",2,"Tows only","Members","Roomy"),
 ("ACA","Schweizer 2-33A","N65804",2,"Tows only","Members","Roomy"),
 ("ACA","IS-28B2 Lark","N350BB",2,"Tows only","Members",""),
 ("JRS","Grob G103 Twin II","N18AG",2,"","Call","Depends on proportions"),
 ("JRS","Schweizer 2-33A (x3)","N17879, N33983, N65976",2,"","Call","Roomy"),
 ("JRS","Schweizer 2-32","N5772S",3,"","Call","Roomy"),
 ("JRS","Schweizer 1-26E","N17933",1,"","Call","Little headroom"),
 ("ASA","Grob G102 Astir CS","N5054",1,"Tows only","Long-distance members","Roomiest here"),
 ("ASA","Grob G103 Twin II","N575AS",2,"Tows only","Long-distance members","Depends on proportions"),
 ("ASA","Grob G103 Twin II","N898AS",2,"Tows only","Long-distance members","Depends on proportions"),
 ("ASA","Grob G103C Twin III","N996T",2,"Tows only","Long-distance members",""),
 ("HHSC","Schleicher ASK-21 (x3)","N521HH, N621HH, N91HH",2,"$50/h guest","Guest","Does not fit you"),
 ("HHSC","Schempp-Hirth Duo Discus","N60BP",2,"$50/h guest","Guest","Front seat reputedly roomy"),
 ("HHSC","Schempp-Hirth Discus CS","N189HH",1,"$50/h guest","Guest",""),
 ("HHSC","Schweizer 1-34","N7654",1,"","Guest",""),
 ("HHSC","Schweizer 1-35C","N3620E",1,"","Guest",""),
 ("HHSC","Schweizer 1-26E (x2)","N2768H, N33874",1,"","Guest","Little headroom"),
 ("HHSC","Schweizer 2-33A (x3)","N17903, N65833, N65839",2,"$50/h guest","Guest","Roomy"),
 ("FLSC","Schleicher ASK-21","N574KS",2,"","Members",""),
 ("FLSC","Grob G102 Astir CS","N20737",1,"","Members","Roomy"),
 ("FLSC","Centrair Pegasus 101B","N70FP",1,"","Members",""),
 ("FLSC","Schweizer 1-26A","N3822A",1,"","Members","15 flights in type required"),
 ("FLSC","Schweizer 2-33A","N234WE",2,"","Members","Roomy"),
 ("VSC","Schleicher ASK-21","N474KS",2,"","Members",""),
 ("VSC","Schweizer 2-33 (x3)","N2463W, N5787S, N7686",2,"","Members","Roomy"),
 ("VSC","Schweizer 1-34","N1172S",1,"","Members",""),
 ("VSC","Schweizer 1-26E","N17924",1,"","Members",""),
 ("LISA","Schweizer 2-33A (x3)","N17956, N2055T, N65918",2,"","Members","Roomy"),
 ("LISA","Schweizer 1-34","N7635",1,"","Members",""),
 ("LISA","Schweizer 1-26E","N17917",1,"","Members",""),
 ("VANSANT","Schweizer 2-33","",2,"$80/h + tow","Yes","Roomy"),
 ("VANSANT","Schweizer 2-32","",3,"$80/h + tow","Yes","Roomy"),
 ("TIGERS","Schweizer 2-33A","N65867",2,"Tows only","Members",""),
 ("TIGERS","Schweizer 1-26B","N389BR",1,"Tows only","Members",""),
 ("TIGERS","Schweizer 1-34","N76JP",1,"Tows only","Members",""),
 ("PGC","Grob G103 family (x5)","N139BG, N5QD, N924BG, N487GC, N5361V",2,"Tows only","Members","Depends on proportions"),
 ("PGC","Grob G102 / Astir CS-77","N131SS, N1006P",1,"Tows only","Members","Roomy"),
 ("PGC","Schempp-Hirth Duo Discus","N90BP",2,"Tows only","Members",""),
 ("PGC","Schweizer 2-22","N91834",2,"Tows only","Members",""),
 ("BSA","Schleicher ASK-21","N214BS",2,"","Members","Does not fit you"),
 ("BSA","LET L-23 Super Blanik","N316BA",2,"","Members","Roomy"),
 ("BSA","Grob G103 Twin Astir","N906BG",2,"","Members",""),
 ("BSA","Schweizer 1-26E (x2)","N1106S, N8642",1,"","Members",""),
 ("PSA","Grob G103","N103X",2,"$10/h","Temp member","Depends on proportions"),
 ("PSA","Grob G102","N412SS / N142SS",1,"$10/h","Temp member (rated)","Roomy"),
 ("PSA","LET L-23 Super Blanik","N916B",2,"$10/h","Temp member","Roomy"),
 ("MASA","Schleicher ASK-21","N899MA",2,"","Members","Does not fit you"),
 ("MASA","Schleicher ASK-21 (hand rudder)","N899SA",2,"","Members","Does not fit you"),
 ("MASA","Schweizer 2-33A","N7782S",2,"","Members","Roomy"),
 ("MASA","Grob G102 Club Astir IIIB","N936BG",1,"","Members",""),
 ("MASA","Rolladen-Schneider LS-4","N30RD",1,"","Members",""),
 ("SKYLINE","Schleicher ASK-21 (x2)","",2,"$39/h","Visiting member","Does not fit you"),
 ("SKYLINE","Schempp-Hirth Discus CS (x2)","",1,"$36/h (3 h cap)","Visiting member","Medium; sit-test"),
 ("SKYLINE","PZL PW-5","",1,"$24/h","Visiting member","Small"),
 ("ESC","Schleicher ASK-13","",2,"$55/h","Closed 2026","Roomy"),
 ("SVS","Schleicher ASK-21","N747SV",2,"","Intro member",""),
 ("SVS","IS-28B2 Lark","",2,"","Intro member",""),
 ("BRSS","Schleicher ASK-21 (x2)","",2,"","Guest member","Does not fit you"),
 ("BRSS","Rolladen-Schneider LS-4 (x2)","",1,"","Guest member",""),
 ("BHS","Schweizer 2-33 (x3)","",2,"","Call","Roomy"),
 ("BHS","Schempp-Hirth Duo Discus","",2,"","Call","Roomy front"),
 ("BHS","Schweizer 1-26A (x3)","",1,"","Call","Small"),
 ("CAROLINA","Grob G103 Acro","",2,"$0/h","Members","Roomy"),
 ("CAROLINA","Grob G102 Standard Astir","",1,"$0/h","Members",""),
 ("MGSA","Schleicher ASK-21 (x2)","",2,"","Members","Does not fit you"),
 ("MGSA","Schempp-Hirth Discus CS","",1,"","Members",""),
 ("MGSA","Grob G102","",1,"","Members",""),
 ("CHIL","Schweizer 2-33A","",2,"$48/h","Yes","Best tall-pilot bet"),
 ("CHIL","PZL PW-6U","",2,"$72/h","Yes","Fairly roomy"),
 ("CHIL","Schweizer 1-26E","",1,"$40/h","Yes","Tight above ~6'2\""),
 ("CHIL","PZL PW-5","",1,"$48/h","Yes","Small"),
 ("CHIL","Schweizer 2-32","",2,"$72/h","Dual only","Very roomy"),
 ("EAGLEVILLE","Schleicher ASK-21","N121FL",2,"","Members","Does not fit you"),
 ("EAGLEVILLE","Schleicher ASK-21","N2237W",2,"","Members","Does not fit you"),
 ("EAGLEVILLE","Rolladen-Schneider LS-4","N68RM",1,"","Members",""),
 ("SKYSOAR","Schweizer 2-33A","",2,"Free to members","Members","Roomy"),
 ("SKYSOAR","SZD-50 Puchacz (KR-03)","",2,"Free to members","Members","Roomy"),
 ("SKYSOAR","PZL PW-5","",1,"Free to members","Members",""),
 ("SKYSOAR","Schweizer 1-34R","",1,"Free to members","Members",""),
 ("CGC","Schleicher ASK-21 (x2)","",2,"$36-40/h","Members","Does not fit you"),
 ("CGC","Schempp-Hirth Duo Discus","",2,"$36-40/h","Members","Roomy front"),
 ("CGC","Schempp-Hirth Discus CS","",1,"$36-40/h","Members",""),
 ("CCSC","Schleicher ASK-21 (x3)","",2,"","Members","Does not fit you"),
 ("CCSC","Schweizer 2-33 (x2)","",2,"","Members","Roomy"),
 ("CCSC","Schweizer 1-26E (x2)","",1,"","Members",""),
 ("CCSC","Grob G102 Std Astir III","",1,"","Members",""),
 ("SANDHILL","Glaser-Dirks DG-505 Orion","",2,"","Guest member","Good"),
 ("SANDHILL","Grob G103 Twin II / Acro II","",2,"","Guest member","Good"),
 ("SANDHILL","Schweizer 2-33","",2,"","Guest member","Roomy"),
 ("SANDHILL","Schempp-Hirth Discus-2cT","",1,"","Guest member",""),
 ("SANDHILL","Schempp-Hirth Open Cirrus","",1,"","Guest member",""),
 ("SEMINOLE","Grob G103 Twin","",2,"$125/h","Yes (with insurance)","Good"),
 ("SEMINOLE","LET L-23 Super Blanik","",2,"$120/h","Yes (with insurance)","Very roomy"),
 ("TBSS","Grob G103 Twin Astir (x3)","",2,"Free to members","Members",""),
 ("TBSS","LET L-23 Blanik (x2)","",2,"Free to members","Members","Roomy"),
 ("TBSS","Schweizer 1-36","",1,"","Members",""),
 ("TBSS","Grob G102","",1,"","Members",""),
 ("TBSS","Rolladen-Schneider LS-4","",1,"","Members","Silver badge required"),
 ("MIAMI","LET L-23 Blanik","",2,"$90/h","Yes (call)","Roomy"),
 ("MIAMI","Schweizer 2-32","",2,"$90/h","Yes (call)","Roomy"),
 ("MIAMI","Pilatus B-4","",1,"$75/h","Yes (call)",""),
 ("TSA","Schleicher ASK-21 (x3)","",2,"","Visiting member","Does not fit you"),
 ("TSA","Schempp-Hirth Duo Discus","",2,"","Visiting member","Front tight above ~6'3\""),
 ("TSA","PZL PW-5 (x3)","",1,"","Visiting member","Small"),
 ("TSA","Schweizer 1-26 (x2)","",1,"","Visiting member","Small"),
 ("SCH","Schweizer 2-33","",2,"$0.20/min","Guest member?","Roomy"),
 ("SCH","LET L-23 / L-33","",2,"$0.40/min","Guest member?","Roomy"),
 ("SCH","Schleicher ASK-21","",2,"$0.60/min","Guest member?","Does not fit you"),
 ("FLF","Schweizer 2-33 (x2)","",2,"$0.25/min","Members","Roomy"),
 ("FLF","Grob G103 Twin Astir","",2,"$0.30/min","Members",""),
 ("FLF","Schweizer 1-26 (x2)","",1,"$0.25/min","Members",""),
 ("FLF","Schweizer 1-36","",1,"$0.25/min","Members",""),
 ("SSB","Glaser-Dirks DG-505","N505PB",2,"$16/flight + $16/h","Limited member","Best chance here"),
 ("SSB","Schleicher ASK-21","N421EF",2,"$16/flight + $16/h","Limited member","Does not fit you"),
 ("SSB","Schempp-Hirth Discus CS","N23SG",1,"$16/flight + $16/h","Limited member","Moderate"),
 ("SSB","Schempp-Hirth Discus CS","N42CA",1,"$16/flight + $16/h","Limited member","Moderate"),
 ("AZS","Schweizer 1-26E","",1,"$40/h (ins. $15k)","Yes","Cramped"),
 ("AZS","Schweizer 1-36","",1,"$45/h (ins. $15k)","Yes","Moderate"),
 ("AZS","Schweizer 2-33A","",2,"$60/h (ins. $15k)","Yes","Roomy"),
 ("AZS","PZL PW-5","",1,"$50/h (ins. $25k)","Yes","Small"),
 ("AZS","Genesis 2","",1,"$70/h (ins. $40k)","Yes","Moderate"),
 ("AZS","Grob G103A","",2,"$75/h (ins. $60k)","Yes","Good; 240 lb limit"),
 ("AZS","Schleicher ASK-21","",2,"$110/h (ins. $100k)","Yes","Does not fit you"),
 ("AZS","MDM-1 Swift (aerobatic)","",1,"$160/flight","Yes","Aerobatic"),
 ("LVVSA","Schweizer 2-33A","",2,"","Members","Roomy"),
 ("LVVSA","LET L-23 Blanik","",2,"","Members","Roomy"),
 ("LVVSA","Schweizer 1-26D","",1,"","Members",""),
 ("LVVSA","Schweizer 2-32 (lease-back)","",3,"","Members","Roomy"),
 ("USA","Grob G103 Twin Astir (x3)","N7813, N80PX, N8485W",2,"","Members","Workable"),
 ("USA","Grob G103 Twin II (x2)","N228BG, N4446Y",2,"","Members","Workable"),
 ("USA","Pilatus B4-PC11","",1,"","Members",""),
]

ACCESS_LABEL = {"VAN":"Van, 4 h or less","VANEDGE":"Van, about 4 h","FLY":"Fly Friday night","FAR":"Out of range"}

# Flight tiers (from travel analysis; KAYAK route pages, Sept 2026)
FLIGHTS = [
 ("A","ORD / MDW","AA, UA / WN","~8-9 pm dep, arr ~10-11 pm CT","$181-308 typ","Sky Soaring ~0:50; Chicago Glider Club ~1:00"),
 ("A","PHL","AA, DL, B6","9:29 pm -> 11:09 pm","$191-347 typ","Van Sant ~1:15; Blairstown ~1:45"),
 ("A","DCA","AA, DL, B6","earlier than 10:48 pm","$185-332 typ","Fairfield PA ~1:30; Skyline"),
 ("A","BWI","WN, DL","10:20 pm -> ~12:00 am","$213-364; last-minute +103%","Fairfield PA ~1:20"),
 ("A","ATL","DL, B6, F9","~8 pm dep","$196-360 typ","Chilhowee ~2:15; MGSA ~1:00"),
 ("A","MCO","B6, DL, F9","7-8 pm dep","$209-395 typ","Seminole-Lake ~0:45"),
 ("A","SYR / BUF","AA, B6, DL","~8:30-9:50 pm","$197-338 typ","Harris Hill 1:45-2:30"),
 ("A","RDU","DL, B6, F9","9:45 pm -> 11:56 pm","$182-346 typ","NCSA ~0:45"),
 ("B","DEN","UA, WN, B6, DL","9:06 pm -> 11:48 pm MT","$278-468; avg $365","Boulder ~0:45"),
 ("B","CLT","AA, DL","8:10 pm -> 10:44 pm","$296-429","Bermuda High ~1:15"),
 ("B","IAD","UA","7:41 pm (tight)","$226-377","Skyline, Eastern Soaring"),
 ("B","PIT","B6, DL","9:59 pm -> 11:55 pm","$233-421","Pittsburgh Soaring ~1:00"),
 ("B","DTW","DL, B6","9:40 pm -> 11:55 pm","$237-416","Sandhill ~1:00"),
 ("B","AUS","DL, B6, WN","7:49 pm -> 11:27 pm CT","$253-470","Fault Line Flyers ~1:15"),
 ("B","TPA","B6, DL","earlier than 9:35 pm","$230-441","Tampa Bay ~0:45; Seminole ~1:15"),
 ("B","BNA","WN, B6, DL","9:29 pm -> 11:23 pm CT","$242-432","Eagleville ~0:45; Chilhowee ~3:00"),
 ("C","PHX","AA, DL, B6","8:29 pm -> 11:21 pm MST","$307-517; avg $398","Arizona Soaring ~0:45"),
 ("C","LAS","B6, DL","8:40 pm -> 11:37 pm PT","$310-542","LVVSA ~0:30"),
 ("C","DFW","AA, DL","7:50 pm -> 11:18 pm CT","$314-540","TSA ~0:50"),
 ("C","SLC","DL, B6","7:30 pm -> 10:55 pm MT","$410-665","Heber ~0:55"),
 ("C","RNO","none nonstop","n/a","n/a","Minden: not reachable Friday night"),
]
